name: bumshakalaka
description: Game for EPAM Social Hackathon

version: 1.0.6

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.0.0
  flame_audio: 1.0.0
  mockito: ^3.0.0
  flutter_vibrate: ^1.3.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/fridge.png
    - assets/images/fridge_big_trimmed.png
    - assets/images/compost.png
    - assets/images/compost_big.png
    - assets/images/compost_big_trimmed.png
    - assets/images/dumpster.png
    - assets/images/dog.png
    - assets/images/dog_big.png
    - assets/images/green_apple.png
    - assets/images/red_apple.png
    - assets/images/apple_core.png
    - assets/images/fish.png
    - assets/images/whole_grilled_chicken.png
    - assets/images/cheese.png
    - assets/images/bone.png
    - assets/images/chicken_thigh_half.png
    - assets/images/lemon.png
    - assets/images/walls.png
    - assets/images/window.png
    - assets/images/window_dry_tree.png
    - assets/images/window_moon.png
    - assets/images/banana_peel.png
    - assets/images/watermelon_peel_big_64_33.png
    - assets/audio/megaman.mp3
    - assets/config.json
  fonts:
    - family: bitmapfont
      fonts:
        - asset: assets/fonts/bitmapfont.ttf